
language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
# Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  #Tagging
  - docker tag udagram-api-feed longtranz/udagram-api-feed:1.3.0
  - docker tag udagram-api-user longtranz/udagram-api-user:1.2.0
  - docker tag udagram-frontend longtranz/udagram-frontend:1.3.0
  - docker tag udagram-reverseproxy longtranz/udagram-reverseproxy:1.0.0

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push longtranz/udagram-api-feed:1.3.0
  - docker push longtranz/udagram-api-user:1.2.0
  - docker push longtranz/udagram-frontend:1.3.0
  - docker push longtranz/udagram-reverseproxy:1.0.0