
language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
# Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker image ls

  #Tagging
  - docker tag udagram-api-feed 987456321258789/udagram-api-feed:latest
  - docker tag udagram-api-user 987456321258789/udagram-api-user:latest
  - docker tag udagram-frontend 987456321258789/udagram-frontend:latest
  - docker tag udagram-reverseproxy 987456321258789/udagram-reverseproxy:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push 987456321258789/udagram-api-feed:latest
  - docker push 987456321258789/udagram-api-user:latest
  - docker push 987456321258789/udagram-frontend:latest
  - docker push 987456321258789/udagram-reverseproxy:latest